### ISSUE TITLE
Please provide web feed

### ISSUE THREAD

**Issue by sjehuda** [cabal-club/cabal-club.github.io#16]
Hello,

Please provide a web feed for Cabal.
You can provide the one that is autogenerated by Mastodon #15.

You can add this code to https://cabal.chat/
`<link href='https://mastodon.social/@Cabal.rss' rel='alternate' type='application/rss+xml'>`

**Comment by hackergrrl** [comment]
Closing this for now. Let's see if anyone has interest+capacity first on #15.

**Comment by sjehuda** [comment]
Hi,

 I'd like you to reconsider it again.

 People would expect to get news from you, not vixe versa, as you (the project cabal) are the preacher.

 It would be wiser to add as many channels as possible, for people who watch you, to get updates from you, instead of waiting for a friend to call, or clicking on the url bar, entering the web address, and visit the webpage, in the hope that something has changed.

 If it was a heavy and expensive to add new channels, I'd understand, yet these channels are easy to add and maintain, and are cheap too.

 Email, RSS, Social etc.

Regards,
Schimon

**Comment by cblgh** [comment]
thanks for your passion & concern @sjehuda. there's currently an ongoing revamp to the website and we'll look into integrating rss in some way for updates on that

soon you'll hopefully be able to follow the updates we send to the open collective over rss at: https://openrss.org/opencollective.com/cabal-club/updates (right now there's just an empty placeholder there)
