### ISSUE TITLE
network requirements

### ISSUE THREAD

**Issue by fenwick67** [cabal-club/cabal-club.github.io#2]
I installed cabal-mobile on a phone and cabal-desktop on a home PC, and I could easily chat locally when they were both on the same LAN. When I turned off wifi on my phone and went to the cell network, I was surprised to find that the clients couldn't connect anymore.  Then, I SSH'ed into a VPS and joined the cabal, and the clients were able to chat again.  

I'm guessing you need at least one client/seeder not behind NAT (for hole-punching?). But I don't see this described anywhere. Could you please describe this on the site?

**Comment by hackergrrl** [comment]
It's possible your cell provider is blocking certain p2p traffic.
