### ISSUE TITLE
Add warning that the cable link from the website does not work the Desktop?

### ISSUE THREAD

**Issue by filipdanic** [cabal-club/cabal-club.github.io#6]
Hey, 👋 new user here and just testing things out

A few folks and I downloaded the desktop client and we managed to create our own cable. But when I join the cable from the website, I just get a blank screen.

Any ideas?

**Comment by filipdanic** [comment]
Okay so now I see there is an issue for that in the other repo: https://github.com/cabal-club/cabal-desktop/issues/93

**Comment by filipdanic** [comment]
Maybe what could be done is to add a note about this. People are going to download the client, paste in the link, and then get disappointed and drop the app.

**Comment by todrobbins** [comment]
Hey @filipdanic,

The new/current [public cabal](cabal://0201400f1aa2e3076a3f17f4521b2cc41e258c446cdaa44742afe6e1b9fd5f82) is working with [cabal-desktop 2.0.0](https://github.com/cabal-club/cabal-desktop/releases/tag/v2.0.0). Try it out and let me know how you get on!

**Comment by cblgh** [comment]
(it works now!)
